name: swm
channels:
  - defaults
dependencies:
  - python=3.6
  - pytorch=1.2
  - torchvision
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - pillow=6.1
  - pip:
    - termcolor
    - torchvision
    - scikit-image